### ISSUE TITLE
5_Bildanalyse Übung 2 l_d Opening

### ISSUE THREAD

**Issue by FelixVolo** [tnt-LUH/Digitale-Bildverarbeitung#4]
Ich weiß zwar nicht wieso das so ist, aber folgende Mängel sind mir an der Lösung aufgefallen:

- Das Eingabebild ist falsch. Es fehlen oben rechts Pixel.
- Das Ergebnis beim Opening ist falsch. Die Form oben links beim Ergebnis ist mit diesem Filterkern eigentlich nicht möglich... und generell sieht das Ergebnis bei mir wenn ich es per Hand mache vollkommen anders aus.

**Comment by FelixVolo** [comment]
Komischerweise bekomme ich das richtige Ergebnis, wenn ich für die Dilatation folgenden Kern anwende:

[0, 0, 0],
[1, 1, 0],
[0, 1, 0]

**Comment by FelixVolo** [comment]
#5

**Comment by TimoK93** [comment]
Kann es sein, dass OpenCV hier eine Faltungs-Operation durchführt? Dann würde die Spiegelung ja passen oder nicht?

**Comment by FelixVolo** [comment]
https://stackoverflow.com/questions/50668212/opencvs-dilate-differs-from-scipy-matlab

Laut der Antwort hier scheint es wohl so.

**Comment by TimoK93** [comment]
Danke! Da sieht man, dass sich ein Code review lohnt :) Wäre vermutlich sonst nie aufgefallen...

**Comment by TimoK93** [comment]
Ich schließe mal, weil die Antwort gefunden wurde. Der Pull Request wird natürlich akzeptiert!

**Comment by TimoK93** [comment]
Habe deinen Pull Request nachbearbeitet: Jetzt so in Ordnung?

**Comment by FelixVolo** [comment]
Nein nicht ganz. Der Kernel wurde zwar transponiert, was zum gewünschten Ergebnis führt, aber erst sollte die Erosion mit dem ursprünglichen Kernel stattfinden und dann die Dilatation (die sogar weg ist) mit den transponierten Kernel.

**Comment by TimoK93** [comment]
Au, sorry. Da habe ich zu viel gelöscht... Sollte jetzt alles soweit drin sein.

**Comment by FelixVolo** [comment]
Habe das mit einer neuen Pull Request korrigiert

**Comment by FelixVolo** [comment]
Okay. Da waren wir wohl gleichzeitig dran. Ich nehme die neue pull request zurück.

**Comment by TimoK93** [comment]
zu spät :)
